import { SLOT, loadSlot, saveSlot } from '../save/storage';
import type { Team } from '../core/types';
import { adaptWorld, type BridgeReport } from '../bridge/adapt';
import { buildFixtureBundle } from '../bridge/fixture';
import { validateBundle, describeCheck } from '../bridge/validate';
import type { MbdArcadeWorldBundleV1 } from '../bridge/contract';

/**
 * WHICH WORLD ARE WE PLAYING IN.
 * ==============================
 *
 * MOONSHOT NINE has its own league — ten clubs on the Meridian Circuit — and it
 * can also be handed one: a Mr. Baseball Dynasty world, thirty-two franchises
 * with real rosters out of a real save. This module owns the choice between
 * them and nothing else; the translation lives in `bridge/`, which is pure and
 * knows nothing about menus or storage.
 *
 * Two rules shape it.
 *
 * **The choice survives a reload, the data might not.** A thirty-two club world
 * is roughly a megabyte of JSON, and localStorage is about five for everything
 * this game owns — including a saved season and a resumable game, which matter
 * more. So the *choice* is always remembered and the *bundle* is remembered only
 * if it fits. When it does not, the game says so in a sentence instead of
 * failing quietly on the next launch.
 *
 * **An imported world is for exhibition play.** That is the contract's own
 * division, not a limitation invented here: an exhibition package is defined for
 * "team selection, local exhibition games, practice, home-run derby, and other
 * non-dynasty modes", and it "produces no importable dynasty receipt". A season
 * or a cup played with MBD clubs would be this game inventing 162 games of
 * dynasty history that MBD has no way to accept — so those modes stay on the
 * Meridian Circuit until a dynasty package and a real importer exist.
 */

export type WorldId = 'meridian' | 'mbd';

interface WorldMemory {
  world: WorldId;
  /** The imported bundle, when it was small enough to keep. */
  bundle?: MbdArcadeWorldBundleV1;
  /** True when the world came from the built-in sample rather than a file. */
  sample?: boolean;
}

export interface LoadedWorld {
  id: WorldId;
  teams: Team[];
  report: BridgeReport | null;
  homeParks: Record<string, string>;
  /** Set when the bundle could not be kept for next time. */
  notPersisted?: boolean;
  label: string;
}

export function meridianWorld(teams: Team[]): LoadedWorld {
  return {
    id: 'meridian',
    teams,
    report: null,
    homeParks: {},
    label: 'The Meridian Circuit',
  };
}

/**
 * Reads a bundle and turns it into a playable world, or explains why not.
 *
 * Validation is the whole point of the seam: everything downstream of here —
 * the team select, the rosters, the game — is entitled to assume the world is
 * internally consistent, because a bundle that was not got stopped here with a
 * sentence naming the rule it broke.
 */
export function loadWorldFrom(
  input: unknown,
  opts: { sample?: boolean; remember?: boolean } = {},
): { world: LoadedWorld } | { error: string; warnings: string[] } {
  const check = validateBundle(input);
  if (!check.ok) {
    return { error: describeCheck(check), warnings: check.warnings.map((w) => w.detail) };
  }
  const bundle = input as MbdArcadeWorldBundleV1;
  const adapted = adaptWorld(bundle);
  if (adapted.teams.length < 2) {
    return { error: 'the world contains fewer than two playable clubs', warnings: [] };
  }

  let notPersisted = false;
  if (opts.remember !== false) {
    const memory: WorldMemory = opts.sample
      ? { world: 'mbd', sample: true }
      : { world: 'mbd', bundle };
    // The sample is regenerated from a seed, so it costs one flag. A real import
    // has to be kept verbatim or it cannot be reproduced, and that is the one
    // that might not fit.
    notPersisted = !saveSlot(SLOT.world, memory);
  }

  return {
    world: {
      id: 'mbd',
      teams: adapted.teams,
      report: adapted.report,
      homeParks: adapted.homeParks,
      notPersisted,
      label: opts.sample
        ? `Mr. Baseball Dynasty — sample world (${adapted.teams.length} clubs)`
        : `Mr. Baseball Dynasty — ${bundle.source.saveId ?? 'exhibition pack'} (${adapted.teams.length} clubs)`,
    },
  };
}

/** The built-in world, for playing MBD clubs before an exporter exists. */
export function loadSampleWorld(): LoadedWorld {
  const result = loadWorldFrom(buildFixtureBundle(), { sample: true });
  // The fixture is generated by this build against this build's own contract,
  // so a validation failure here is a bug in the bridge rather than bad input —
  // and there is no sensible way to continue past it.
  if ('error' in result) throw new Error(`the sample world failed its own validation: ${result.error}`);
  return result.world;
}

/** What was chosen last time, re-derived. Null means the Meridian Circuit. */
export function restoreWorld(): LoadedWorld | null {
  const memory = loadSlot<WorldMemory>(SLOT.world);
  if (!memory || memory.world !== 'mbd') return null;
  try {
    if (memory.sample) return loadSampleWorld();
    if (!memory.bundle) return null;
    const result = loadWorldFrom(memory.bundle, { remember: false });
    return 'error' in result ? null : result.world;
  } catch {
    // A stored world that no longer loads is not worth crashing over; the
    // Meridian Circuit is always there.
    return null;
  }
}

export function forgetWorld(): void {
  saveSlot(SLOT.world, { world: 'meridian' } satisfies WorldMemory);
}

/**
 * Asks for a `.json` file and hands back whatever was in it.
 *
 * Deliberately not drag-and-drop and not a URL fetch: a bundle is somebody's
 * dynasty, and the only way it should arrive is because they went and got it.
 */
export function pickBundleFile(): Promise<unknown | null> {
  return new Promise((resolve) => {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = 'application/json,.json';
    input.style.display = 'none';
    const done = (value: unknown | null) => {
      input.remove();
      resolve(value);
    };
    input.addEventListener('change', () => {
      const file = input.files?.[0];
      if (!file) return done(null);
      const reader = new FileReader();
      reader.onerror = () => done(null);
      reader.onload = () => {
        try {
          done(JSON.parse(String(reader.result)));
        } catch {
          // Not JSON at all. Distinguished from "JSON that is not a bundle",
          // which the validator reports in its own words.
          done({ __unparseable: true });
        }
      };
      reader.readAsText(file);
    });
    // Safari will not open a picker for an element that is not in the document.
    document.body.appendChild(input);
    input.click();
  });
}

/** The bridge report as a readable pane. */
export function reportHtml(world: LoadedWorld): string {
  if (!world.report) {
    return `<div class="menu-hint world-report"><h4>THE MERIDIAN CIRCUIT</h4><p>Ten clubs, two divisions, every player original to this game. Seasons and the cup live here.</p></div>`;
  }
  const r = world.report;
  const list = (items: string[]) =>
    items.length ? `<ul>${items.map((i) => `<li>${esc(i)}</li>`).join('')}</ul>` : '<p>None.</p>';
  return `
    <div class="menu-hint world-report">
      <h4>${esc(world.label.toUpperCase())}</h4>
      <p><b>${r.teams}</b> clubs &middot; <b>${r.players}</b> players available to play.</p>
      ${world.notPersisted ? '<p class="world-warn">Too large to keep for next launch &mdash; it will need importing again.</p>' : ''}
      <h5>MADE UP BY THIS GAME</h5>
      ${list(r.derived)}
      <h5>CARRIED BY MBD, NOT USED HERE</h5>
      ${list(r.ignored)}
      ${r.notes.length ? `<h5>NOTES</h5>${list(r.notes.slice(0, 5))}` : ''}
    </div>`;
}

function esc(s: string): string {
  return s.replace(/[&<>"]/g, (c) => `&#${c.charCodeAt(0)};`);
}
