/**
 * EXPORT A REAL MBD WORLD.
 * ========================
 *
 *   npx tsx scripts/export-mbd-world.ts --mbd ../MBD --out public/mbd-world.json
 *
 * **This is a stand-in, and it is in the wrong repository on purpose.**
 *
 * The arcade-world handoff is clear that the exporter is MBD's first slice —
 * "shared contracts, pure adapter, all 32 teams, exact save rosters/ratings,
 * assets manifest, deterministic JSON, and round-trip validation" — and that it
 * has to run inside MBD, through MBD's save coordinator, over a real save. None
 * of that can happen here. When that exists, this file is deleted.
 *
 * What it does in the meantime is the one thing worth doing: it runs **MBD's
 * own code**, from a checkout, rather than re-implementing it. A faithful port
 * of a 36 kB generator would be a second copy of somebody else's canon that
 * starts drifting the moment either side is touched, and the drift would be
 * invisible — the players would just quietly stop being MBD's players. So this
 * imports `generateLeaguePlayers`, `buildRosterState` and the franchise table
 * straight out of `packages/sim-core`, mirrors `buildNewGameState`'s opening
 * sequence, and writes what MBD produced.
 *
 * Three things it deliberately does not carry across:
 *
 *   HIDDEN TRUTH   ceiling, floor, potential, development program and
 *                  trajectory. The contract forbids exporting scouting truth
 *                  into a match package, and MBD attaches those in a later step
 *                  (`initializePlayerDevelopmentProfile`) that this skips
 *                  entirely rather than generating and then deleting.
 *   MONEY          contracts, salaries, arbitration, service time. Nothing in a
 *                  played game reads them and a receipt may not change them.
 *   THE MINORS     an exhibition package needs the people who can take the
 *                  field. The affiliates are generated by MBD all the same;
 *                  they are simply not written out.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

// The bundle shape is this repository's business, so it comes from here.
import {
  BRIDGE_VERSION,
  BUNDLE_FORMAT,
  type ArcadeHitterRatings,
  type ArcadeOrganizationRoster,
  type ArcadePitcherRatings,
  type ArcadePlayer,
  type ArcadePosition,
  type ArcadeTeam,
  type MbdArcadeWorldBundleV1,
} from '../src/bridge/contract';
import { makeRating } from '../src/bridge/rating';

interface Args {
  mbd: string;
  out: string;
  seed: number;
}

function parseArgs(argv: string[]): Args {
  const get = (name: string, fallback?: string): string => {
    const i = argv.indexOf(`--${name}`);
    if (i >= 0 && argv[i + 1]) return argv[i + 1];
    if (fallback !== undefined) return fallback;
    throw new Error(`missing --${name}`);
  };
  return {
    mbd: resolve(get('mbd')),
    out: resolve(get('out', 'public/mbd-world.json')),
    // MBD's own new-game seed. Changing it produces a different opening day,
    // exactly as starting a new dynasty with a different seed would.
    seed: Number(get('seed', '1')),
  };
}

/** Imports a module out of the MBD checkout by absolute path. */
async function fromMbd<T>(root: string, rel: string): Promise<T> {
  return (await import(pathToFileURL(resolve(root, rel)).href)) as T;
}

// MBD's position codes are already the contract's.
const PITCHER_POS = new Set(['SP', 'RP', 'CL']);

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  console.log(`reading MBD from ${args.mbd}`);

  const { TEAMS } = await fromMbd<{ TEAMS: readonly MbdTeamDef[] }>(
    args.mbd,
    'packages/sim-core/src/league/teams.ts',
  );
  const { GameRNG } = await fromMbd<{ GameRNG: new (seed: number) => MbdRng }>(
    args.mbd,
    'packages/sim-core/src/math/prng.ts',
  );
  const { generateLeaguePlayers } = await fromMbd<{
    generateLeaguePlayers: (
      rng: MbdRng,
      teamIds: string[],
      options: { authoredPlayersByTeam?: Map<string, unknown[]> },
    ) => MbdPlayer[];
  }>(args.mbd, 'packages/sim-core/src/player/generation.ts');
  const { buildRosterState } = await fromMbd<{
    buildRosterState: (teamId: string, players: MbdPlayer[]) => MbdRosterState;
  }>(args.mbd, 'packages/sim-core/src/roster/rosterManager.ts');
  const { getMinorLeaguePlayerGenerationContent } = await fromMbd<{
    getMinorLeaguePlayerGenerationContent: () => Map<string, unknown[]>;
  }>(args.mbd, 'apps/web/src/workers/content/minorLeagueContent.ts');

  const colours = readTeamColours(args.mbd);
  console.log(`read ${Object.keys(colours).length} club palettes from TeamLogo.tsx`);

  // The opening sequence from MBD's own `buildNewGameState`, in its own order.
  // `rng.fork()` matters: reproducing it out of order would produce a different
  // league from the same seed, which is a subtle way of not actually exporting
  // MBD's opening day.
  const rng = new GameRNG(args.seed);
  const teamIds = TEAMS.map((t) => t.id);
  const players = generateLeaguePlayers(rng.fork(), teamIds, {
    authoredPlayersByTeam: getMinorLeaguePlayerGenerationContent(),
  });
  console.log(`MBD generated ${players.length} players across ${teamIds.length} organisations`);

  const byTeam = new Map<string, MbdPlayer[]>();
  for (const p of players) {
    const list = byTeam.get(p.teamId) ?? [];
    list.push(p);
    byTeam.set(p.teamId, list);
  }

  const outTeams: ArcadeTeam[] = [];
  const outPlayers: ArcadePlayer[] = [];
  const outOrgs: ArcadeOrganizationRoster[] = [];

  for (const def of TEAMS) {
    const roster = buildRosterState(def.id, players);
    const all = byTeam.get(def.id) ?? [];
    const active = new Set(roster.mlbRoster);
    // Only the people who can take the field. The affiliates exist in MBD and
    // are simply not part of an exhibition package.
    const mlb = all.filter((p) => active.has(p.id));

    // MBD's own deterministic policy, from `buildGameTeam` in the season
    // simulator: hitters by overall, top nine bat; pitchers by overall, the
    // first starter starts and the rest are the bullpen. Copied because the
    // handoff asks the exporter to resolve absent plan slots with MBD's policy
    // rather than one invented at the boundary.
    const hitters = mlb
      .filter((p) => !PITCHER_POS.has(p.position))
      .sort((a, b) => b.overallRating - a.overallRating);
    const pitchers = mlb
      .filter((p) => PITCHER_POS.has(p.position))
      .sort((a, b) => b.overallRating - a.overallRating);
    const lineup = hitters.slice(0, 9);
    const rotation = pitchers.filter((p) => p.position === 'SP').slice(0, 5);
    const relievers = pitchers.filter((p) => !rotation.includes(p));

    outTeams.push({
      id: def.id,
      city: def.city,
      name: def.name,
      fullName: `${def.city} ${def.name}`,
      abbreviation: def.abbreviation,
      division: def.division,
      parkFactor: def.parkFactor,
      branding: {
        ...colourFor(colours, def.id),
        logoAsset: `logos/${def.id}.svg`,
      },
      identity: { archetype: null, franchiseHook: null, marketSize: null },
    });

    for (const p of mlb) outPlayers.push(toArcadePlayer(p));

    outOrgs.push({
      teamId: def.id,
      active26PlayerIds: roster.mlbRoster,
      fortyManPlayerIds: roster.fortyManRoster.filter((id) => active.has(id)),
      affiliates: [],
      defaults: {
        lineupPlayerIds: lineup.map((p) => p.id),
        rotationPlayerIds: rotation.map((p) => p.id),
        bullpen: {
          closerId: relievers.find((p) => p.position === 'CL')?.id ?? relievers[0]?.id ?? null,
          setupIds: relievers.slice(0, 2).map((p) => p.id),
          longReliefId: relievers[relievers.length - 1]?.id ?? null,
          otherRelieverIds: relievers.slice(2, -1).map((p) => p.id),
        },
        benchPlayerIds: hitters.slice(9).map((p) => p.id),
      },
    });
  }

  const bundle: MbdArcadeWorldBundleV1 = {
    format: BUNDLE_FORMAT,
    bridgeVersion: BRIDGE_VERSION,
    mode: 'exhibition',
    source: {
      game: 'Mr. Baseball Dynasty',
      snapshotSchemaVersion: 48,
      // No save: this is opening day of a brand-new league, not somebody's
      // dynasty. A dynasty package must name a save; an exhibition one may not.
      saveId: null,
      season: 1,
      day: 1,
      phase: 'preseason',
      sourceSnapshotHash: `mbd-newgame-seed-${args.seed}`,
      bundleHash: `mbd-newgame-seed-${args.seed}-v${BRIDGE_VERSION}`,
    },
    league: {
      id: 'mbd',
      name: 'Mr. Baseball Dynasty',
      positions: ['C', '1B', '2B', '3B', 'SS', 'LF', 'CF', 'RF', 'DH', 'SP', 'RP', 'CL'],
      organizationLevels: ['MLB', 'AAA', 'AA', 'A_PLUS', 'A', 'ROOKIE', 'INTERNATIONAL'],
      playerStatuses: [
        'MLB',
        'AAA',
        'AA',
        'A_PLUS',
        'A',
        'ROOKIE',
        'INTERNATIONAL',
        'FREE_AGENT',
        'RETIRED',
      ],
      rules: {
        regulationInnings: 9,
        battingOrderSize: 9,
        activeRosterLimit: 26,
        fortyManRosterLimit: 40,
        defaultRotationSize: 5,
        designatedHitter: true,
      },
    },
    teams: outTeams,
    organizations: outOrgs,
    players: outPlayers,
    presentation: {
      standings: outTeams.map((t) => ({
        teamId: t.id,
        wins: 0,
        losses: 0,
        gamesBack: 0,
        streak: '-',
      })),
      rivalry: null,
      playerNicknames: [],
      featuredMoments: [],
      recordsInReach: [],
    },
    game: null,
  };

  mkdirSync(dirname(args.out), { recursive: true });
  // Stable key order and no whitespace: this file is committed, so a re-export
  // that changed nothing should produce a diff of nothing.
  writeFileSync(args.out, JSON.stringify(bundle));
  const kb = Math.round(JSON.stringify(bundle).length / 1024);
  console.log(
    `wrote ${args.out} — ${outTeams.length} clubs, ${outPlayers.length} players, ${kb} kB`,
  );
}

/**
 * MBD's club colours, scraped out of a React component.
 *
 * They live in `apps/web/src/shared/components/TeamLogo.tsx` rather than in
 * shared data — gap #7 in the handoff, and the reason this reads like a hack.
 * It is a hack, and the alternative is worse: transcribing thirty-two palettes
 * into this repository by hand produces a copy that silently stops matching the
 * day somebody adjusts a shade.
 *
 * It fails loudly rather than falling back, because a partial read would ship
 * a league where some clubs wear the wrong colours and nothing said so.
 */
function readTeamColours(root: string): Record<string, Palette> {
  const src = readFileSync(
    resolve(root, 'apps/web/src/shared/components/TeamLogo.tsx'),
    'utf8',
  );
  const out: Record<string, Palette> = {};
  const re = /(\w+):\s*\{\s*bg:\s*'(#[0-9a-fA-F]{6})',\s*text:\s*'(#[0-9a-fA-F]{6})',\s*accent:\s*'(#[0-9a-fA-F]{6})'\s*\}/g;
  for (let m = re.exec(src); m; m = re.exec(src)) {
    out[m[1]] = { background: m[2], text: m[3], accent: m[4] };
  }
  return out;
}

function colourFor(colours: Record<string, Palette>, id: string): Palette {
  const c = colours[id];
  if (!c) {
    throw new Error(
      `no palette for "${id}" in TeamLogo.tsx — the colour map moved or changed shape`,
    );
  }
  return c;
}

interface Palette {
  background: string;
  text: string;
  accent: string;
}

/**
 * One MBD player as a bridge player.
 *
 * Everything here is a straight translation. The fields that are *absent* are
 * the point: no ceiling, no floor, no potential, no development program, no
 * contract, no service time. A game does not need them and the contract says a
 * match package may not carry them.
 */
function toArcadePlayer(p: MbdPlayer): ArcadePlayer {
  const h: ArcadeHitterRatings = {
    contact: makeRating(p.hitterAttributes.contact),
    power: makeRating(p.hitterAttributes.power),
    eye: makeRating(p.hitterAttributes.eye),
    speed: makeRating(p.hitterAttributes.speed),
    defense: makeRating(p.hitterAttributes.defense),
    durability: makeRating(p.hitterAttributes.durability),
  };
  const pitcher: ArcadePitcherRatings | null = p.pitcherAttributes
    ? {
        stuff: makeRating(p.pitcherAttributes.stuff),
        control: makeRating(p.pitcherAttributes.control),
        stamina: makeRating(p.pitcherAttributes.stamina),
        velocity: makeRating(p.pitcherAttributes.velocity),
        movement: makeRating(p.pitcherAttributes.movement),
      }
    : null;

  return {
    id: p.id,
    teamId: p.teamId,
    firstName: p.firstName,
    lastName: p.lastName,
    displayName: `${p.firstName} ${p.lastName}`,
    age: p.age,
    nationality: p.nationality,
    primaryPosition: p.position as ArcadePosition,
    rosterStatus: 'MLB',
    minorLeagueLevel: null,
    // Position text alone is not enough — the attributes decide.
    canPitch: pitcher !== null,
    hitter: h,
    pitcher,
    overall: makeRating(p.overallRating),
    personality: {
      workEthic: p.personality.workEthic,
      mentalToughness: p.personality.mentalToughness,
      leadership: p.personality.leadership,
      competitiveness: p.personality.competitiveness,
      traits: p.personalityTraits ?? [],
    },
    availability: {
      // Opening day of a new league: nobody is hurt yet.
      eligible: true,
      reason: 'available',
      injuryType: null,
      injurySeverity: null,
      daysRemaining: null,
      injuryAttributePenalty: null,
      rehabPlan: null,
      workloadMode: null,
      workloadLimitOuts: null,
    },
    presentationOnly: {
      // MBD has none of these. Null rather than invented, so the receiving game
      // derives them visibly and nothing mistakes a default for a fact.
      bats: null,
      throws: null,
      jerseyNumber: null,
      heightInches: null,
      weightPounds: null,
      pitchTypes: [],
      secondaryPositions: [],
      provenance: 'unknown',
    },
  };
}

// ---- the shapes this script reads out of MBD, named locally so a change on
// ---- that side is a type error here rather than a silent wrong export.

interface MbdTeamDef {
  id: string;
  name: string;
  city: string;
  abbreviation: string;
  division: ArcadeTeam['division'];
  parkFactor: number;
}

interface MbdRng {
  fork(): MbdRng;
}

interface MbdRosterState {
  teamId: string;
  mlbRoster: string[];
  fortyManRoster: string[];
}

interface MbdPlayer {
  id: string;
  firstName: string;
  lastName: string;
  age: number;
  position: string;
  teamId: string;
  nationality: 'american' | 'latin' | 'asian';
  overallRating: number;
  rosterStatus: string;
  hitterAttributes: {
    contact: number;
    power: number;
    eye: number;
    speed: number;
    defense: number;
    durability: number;
  };
  pitcherAttributes: {
    stuff: number;
    control: number;
    stamina: number;
    velocity: number;
    movement: number;
  } | null;
  personality: {
    workEthic: number;
    mentalToughness: number;
    leadership: number;
    competitiveness: number;
  };
  personalityTraits?: string[];
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
